<h1> Biomass Regression Model </h1>

In [1]:
import array
from PIL import Image, ImageDraw
import numpy as np
import pandas as pd
import json
import math
import statsmodels.api as sm
from matplotlib import pyplot as plt
pd.set_option('display.height', 500)
pd.set_option('display.max_rows', 500)

%matplotlib inline

<h1> Create dataframe with relevant features </h1>

In [2]:
data_dir_base = '/root/data/blender_v3/'
COMPLETE_SAMPLE_SIZE = 4007
df = pd.DataFrame()
for idx in range(COMPLETE_SAMPLE_SIZE):
    # get annotation data
    annotation_file_name = 'annot_{}.json'.format(idx)
    annotation_file_path = '{}/{}/{}'.format(data_dir_base, 'annotations', annotation_file_name)
    annotation_data = json.load(open(annotation_file_path, 'rb'))
    df = df.append(annotation_data, ignore_index=True)

# add columns to DataFrame
df['log_volume'] = np.log(df.volume)
df['log_length'] = np.log(df.length)
df['log_width'] = np.log(df.height)
df['log_breadth'] = np.log(df.width)

<h1> Simple Allometric Models </h1>

We first consider the model $ W = al^b $, where $W$ and $l$ represent biomass and weight, respectively. First, rewrite the model as $\log{W} = a + b\log{l}$. We will fit the points to this model.

In [3]:
features = ['log_length']
target = 'log_volume'

model = sm.OLS(df[target], df.filter(features)).fit()
print(model.summary())

A = np.vstack([df.filter(features).values.T, np.ones(df.shape[0])]).T
res = np.linalg.lstsq(A, df[target].values)
b, a = res[0]

                            OLS Regression Results                            
Dep. Variable:             log_volume   R-squared:                       0.998
Model:                            OLS   Adj. R-squared:                  0.998
Method:                 Least Squares   F-statistic:                 1.927e+06
Date:                Thu, 14 Jun 2018   Prob (F-statistic):               0.00
Time:                        20:10:26   Log-Likelihood:                -1558.2
No. Observations:                4007   AIC:                             3118.
Df Residuals:                    4006   BIC:                             3125.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
log_length     1.7590      0.001   1388.162      0.0

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


In [4]:
df

focal_length     height  interocular_distance      length  \
0              1.0  20.760459                  0.65  103.802296   
1              1.0  21.529521                  0.65  107.647604   
2              1.0  22.001732                  0.65  110.008658   
3              1.0  18.319376                  0.65   91.596881   
4              1.0  18.734798                  0.65   93.673988   
5              1.0  16.761576                  0.65   83.807878   
6              1.0  20.545638                  0.65  102.728189   
7              1.0  21.861212                  0.65  109.306060   
8              1.0  23.221622                  0.65  116.108112   
9              1.0  11.978642                  0.65   59.893212   
10             1.0  22.739985                  0.65  113.699926   
11             1.0  12.852590                  0.65   64.262951   
12             1.0  12.988791                  0.65   64.943954   
13             1.0  19.946522                  0.65   99.732609   
14             1.0  16.937225                  0.65   84.686123   
15             1.0  21.109892                  0.65  105.549461   
16             1.0  16.765707                  0.65   83.828534   
17             1.0  16.339764                  0.65   81.698822   
18             1.0  24.113331                  0.65  120.566653   
19             1.0  19.468229                  0.65   97.341144   
20             1.0  10.877890                  0.65   54.389448   
21             1.0  10.560039                  0.65   52.800196   
22             1.0  17.086066                  0.65   85.430332   
23             1.0   9.420368                  0.65   47.101840   
24             1.0  18.457711                  0.65   92.288557   
25             1.0  23.845532                  0.65  119.227661   
26             1.0  21.627026                  0.65  108.135131   
27             1.0  18.166849                  0.65   90.834245   
28             1.0  19.296378                  0.65   96.481888   
29             1.0  23.767842                  0.65  118.839211   
30             1.0  19.452339                  0.65   97.261697   
31             1.0  10.296083                  0.65   51.480414   
32             1.0  14.367074                  0.65   71.835368   
33             1.0  13.286883                  0.65   66.434415   
34             1.0  23.937603                  0.65  119.688014   
35             1.0  23.175168                  0.65  115.875841   
36             1.0  11.259339                  0.65   56.296697   
37             1.0  11.227117                  0.65   56.135586   
38             1.0  12.421413                  0.65   62.107066   
39             1.0  14.390515                  0.65   71.952575   
40             1.0  18.081739                  0.65   90.408693   
41             1.0  23.417646                  0.65  117.088228   
42             1.0  18.192420                  0.65   90.962098   
43             1.0  22.242619                  0.65  111.213095   
44             1.0   9.810571                  0.65   49.052854   
45             1.0  11.686669                  0.65   58.433343   
46             1.0  13.573040                  0.65   67.865198   
47             1.0  19.439428                  0.65   97.197141   
48             1.0  17.303563                  0.65   86.517817   
49             1.0  23.919584                  0.65  119.597921   
50             1.0  16.717497                  0.65   83.587487   
51             1.0  22.951644                  0.65  114.758219   
52             1.0  16.111469                  0.65   80.557346   
53             1.0  16.395757                  0.65   81.978786   
54             1.0  23.272686                  0.65  116.363432   
55             1.0  23.308180                  0.65  116.540902   
56             1.0  25.568175                  0.65  127.840877   
57             1.0  20.620747                  0.65  103.103736   
58             1.0  17.089910                  0.65  

Now consider the following model, which is the first model but generalized to incorporate other dimensions as well (width and breadth):

$$W=al^b w^c b^d$$

Here, $W$, $l$, $w$ and $b$ represent biomass, length, width, and breadth, respectively. Taking logarithms, this gives 

$$ \log{W} = a + b\log{l} + c\log{w} + d\log{b} $$

In [15]:
features = ['log_length', 'log_width', 'log_breadth']
target = 'log_volume'

model = sm.OLS(df[target], df.filter(features)).fit()
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:             log_volume   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.663e+11
Date:                Thu, 24 May 2018   Prob (F-statistic):               0.00
Time:                        23:17:38   Log-Likelihood:                 30051.
No. Observations:                4007   AIC:                        -6.010e+04
Df Residuals:                    4005   BIC:                        -6.009e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
log_length     -0.2384   1.18e-05  -2.02e+04      

ValueError: too many values to unpack (expected 2)

In [19]:
model.params

log_length    -0.238440
log_width      1.517973
log_breadth    1.716944
dtype: float64

In [16]:
features = ['log_length', 'log_width', 'log_breadth']
A = np.vstack([df[features].values.T, np.ones(df.shape[0])]).T
res = np.linalg.lstsq(A, df[target].values)


In [5]:
np.dot(res[0].T, A.T)

array([[ 8.39167452,  8.50067115,  8.56568289, ...,  7.32076955,
         8.72807741,  8.77813947]])

In [6]:
np.dot(res[0].T, A.T)

array([[ 8.39167452,  8.50067115,  8.56568289, ...,  7.32076955,
         8.72807741,  8.77813947]])

In [7]:
res[0].T.shape, A.T.shape

((1, 4), (4, 4007))

In [10]:
res

(array([ -7.19356492e+07,   9.15796487e+07,  -1.96439965e+07,
          1.12194436e+08]),
 array([], dtype=float64),
 3,
 array([  3.60299720e+02,   8.58442905e+00,   1.08146712e-13,
          9.54306990e-15]))

<h1> k-fold Cross Validation </h1>

In [8]:
results_df = pd.DataFrame()

# specify the allometric models that we want to compare

models = {}
models['model_1'] = {
    'features': ['log_length'],
    'target': 'log_volume'
}
models['model_2'] = {
    'features': ['log_length', 'log_width', 'log_breadth'],
    'target': 'log_volume'
}

# specify the cross validation size
k = 10

# perform k-fold cross validation for all of the models
bucket_endpoints = np.linspace(0, df.shape[0], k + 1).round()
for model_name, model in models.items():
    features = model['features']
    target = model['target']
    for idx in range(len(bucket_endpoints)-1):
        # specify in-sample and out-of-sample subsets
        out_of_sample_mask = (df.index >= bucket_endpoints[idx]) & (df.index < bucket_endpoints[idx+1])
        in_sample_data = df.loc[~out_of_sample_mask].copy(deep=True)
        
        # train the model
        A_in_sample = np.vstack([in_sample_data[features].values.T, np.ones(in_sample_data.shape[0])]).T
        res = np.linalg.lstsq(A_in_sample, in_sample_data[target])
        
        # test the model on out of sample data (the performance metric we will use here is mean squared error)
        out_of_sample_data = df.loc[out_of_sample_mask].copy(deep=True)
        A_out_of_sample = np.vstack([out_of_sample_data[features].values.T, np.ones(out_of_sample_data.shape[0])]).T
        out_of_sample_data['prediction'] = np.dot(res[0].T, A_out_of_sample.T)[0]
        print 
        
        # compute mean squared eror
        mse = ((out_of_sample_data['prediction'] - out_of_sample_data[target])**2).mean()
        line_to_append = {
            'model_name': model_name,
            'features': features,
            'target': target,
            'mse': mse
        }
        results_df = results_df.append(line_to_append, ignore_index=True)
        
        
        

    
    


In [9]:
results_df

features model_name       mse      target
0                           [log_length]    model_1  1.216388  log_volume
1                           [log_length]    model_1  1.727250  log_volume
2                           [log_length]    model_1  1.901433  log_volume
3                           [log_length]    model_1  0.770773  log_volume
4                           [log_length]    model_1  1.294196  log_volume
5                           [log_length]    model_1  3.821907  log_volume
6                           [log_length]    model_1  2.336363  log_volume
7                           [log_length]    model_1  1.956853  log_volume
8                           [log_length]    model_1  0.974054  log_volume
9                           [log_length]    model_1  3.687536  log_volume
10  [log_length, log_width, log_breadth]    model_2  1.216389  log_volume
11  [log_length, log_width, log_breadth]    model_2  1.727250  log_volume
12  [log_length, log_width, log_breadth]    model_2  1.901433  log_volume
13  [log_length, log_width, log_breadth]    model_2  0.770773  log_volume
14  [log_length, log_width, log_breadth]    model_2  1.294196  log_volume
15  [log_length, log_width, log_breadth]    model_2  3.821906  log_volume
16  [log_length, log_width, log_breadth]    model_2  2.336362  log_volume
17  [log_length, log_width, log_breadth]    model_2  1.956853  log_volume
18  [log_length, log_width, log_breadth]    model_2  0.974053  log_volume
19  [log_length, log_width, log_breadth]    model_2  3.687535  log_volume